Repository Team-with-suhyeon/With-Suhyeon-Android, pull requests merged in 2025-01, with the labels that each got.

#6 [FEAT/#4] Color, Font 기초 세팅
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Color.kt
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Theme.kt
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Type.kt
  app/src/main/res/font/suit.ttf
Labels: ⭐ [FEAT], ⚙️ [SETTING], 🐬 세호

#5 [FEAT/#3] Jetpack Navigation, SAA 기초세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/contract/ChatContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/navigation/ChatNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/contract/FindSuhyeonContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/navigation/FindSuhyeonNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/contract/GalleryContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/contract/HomeContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainActivity.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainTab.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainBottomBar.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/MyPageScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/contract/MyPageContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/contract/OnBoardingContract.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/navigation/OnBoardingNavigation.kt
  app/src/main/res/drawable/ic_find.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_message.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💛 COMPOSE, ⭐ [FEAT], ⚙️ [SETTING], 🍼 지현

#16 [FEAT/#7] 공통 컴포넌트 구현 - DateTimePicker, YearPicker, 플로팅 버튼, LongTextfield
  app/build.gradle.kts
  app/src/main/java/com/sopt/withsuhyeon/core/component/DummyComponent.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/floatingbutton/AddFindSuhyeonPostButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/floatingbutton/AddGalleryPostButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/picker/DateTimePicker.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/picker/YearPicker.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/LongTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/size/CalculateWidth.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/time/TimeUtil.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Type.kt
  app/src/main/res/drawable/ic_plus_24.xml
  app/src/main/res/font/suit_bold.ttf
  app/src/main/res/font/suit_regular.ttf
  app/src/main/res/font/suit_semibold.ttf
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 💙 [UI], 🌻 윤서

#15 [FEAT/#9] 공통 컴포넌트 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/button/BasicButtonForTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/progressbar/AnimatedProgressBar.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextFieldForPrice.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/modifier/ModifierExt.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/price/VisualTransformation.kt
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, 💙 [UI], 🍀 지현

#18 [FEAT/#8] 공통 컴포넌트 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/CheckBox.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/LargeButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/ShowButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/SmallButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/KeyStorage.kt
  app/src/main/res/drawable/ic_check_16.xml
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🐬 세호

#20 [HOTFIX/#19] Font 세팅 변경사항 반영
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Type.kt
Labels: 😮 [HOTFIX], ⚙️ [SETTING], 🌻 윤서

#22 [FEAT/#14] 컴포넌트 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/MediumChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/SmallChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/dropdown/basic/BasicSelectDropDown.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/dropdown/chip/MediumChipDropDown.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/dropdown/text/TextDropDown.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/dropdown/text/TextDropDownItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/dropdown/text/TextSelectDropDownWithIcon.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/progressbar/AnimatedProgressBar.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/type/DateChipType.kt
  app/src/main/java/com/sopt/withsuhyeon/core/type/MediumChipType.kt
  app/src/main/java/com/sopt/withsuhyeon/core/type/SmallChipType.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/price/DecimalFormater.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DateChipListRow.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DetailMeetingInformation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/FindSuhyeonPostItem.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/MultiSelectRequirements.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/SingleSelectGender.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/chip/DateChip.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/chip/LargeSelectChip.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/chip/SmallSelectChip.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/drpodown/DetailMeetingInformationDropDown.kt
  app/src/main/java/com/sopt/withsuhyeon/ui/theme/Color.kt
  app/src/main/res/drawable/dummy_ellipse.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_calander.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, 💙 [UI], 🍀 지현

#27 [FIX/#26] DateTimePicker minute 단위 수정, 올림 반영
  app/src/main/java/com/sopt/withsuhyeon/core/component/picker/DateTimePicker.kt
Labels: 💙 [UI], 🔧 [FIX], 🌻 윤서

#28 [UI/#25] 지역 선택 컴포넌트 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/MainLocationChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/SubLocationChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/menu/LocationMenu.kt
Labels: 💛 COMPOSE, 💙 [UI], 🍀 지현

#34 [FEAT/#12] 컴포넌트 구현, 갤러리 메인 뷰 및 애니메이션 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/GalleryCategoryBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/button/SmallButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/card/GalleryMainCardItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/categoryrow/GalleryMainCategoryAnimatedRow.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/categoryrow/GalleryMainFullCategoryRow.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/categoryrow/GalleryMainShortCategoryRow.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/AnimatedGalleryMainCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/CategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/GalleryMainFullCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/GalleryMainShortCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/NewCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/floatingbutton/AnimatedAddPostButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/modal/AlertModal.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/profile/PostProfileInfoRow.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/topbar/TopNavBar.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainScreen.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🌻 윤서

#31 [UI/#29] post bottom bar
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottombar/PostBottomBar.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DetailMeetingInformation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainBottomBar.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ [CHORE], 💛 COMPOSE, 💙 [UI], 🍀 지현

#38 [FEAT/#30] 이미지 퍼미션 기초 세팅, 갤러리 뷰 및 네비게이션 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/DeletePostBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/GalleryCategoryBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/button/DeleteLargeButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/button/SmallButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/card/GalleryMainCardItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/floatingbutton/AnimatedAddPostButton.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/modal/AlertModal.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/LongTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryPostDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryUploadScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryUploadWithPicker.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingScreen.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🌻 윤서

#40 [FEAT/#39] 전체 채팅방 뷰 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/list/TotalChatRoomList.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/listitem/ChatRoomListItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/type/SmallChipType.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/ChatRoomModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🌻 윤서

#43 [FEAT/#42] 마이페이지 메인 뷰 구현
  app/src/main/java/com/sopt/withsuhyeon/WithSuhyeonApplication.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/MyPageScreen.kt
  app/src/main/res/drawable/ic_block.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/values/strings.xml
Labels: 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🌻 윤서

#47 [FEAT/#46] 수현이 찾기 네비게이션 연결
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/DateTimePickerBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicShortTextFieldForPrice.kt
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonPostScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DateChipListRow.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/navigation/FindSuhyeonNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
Labels: 🛠️ [CHORE], 💛 COMPOSE, ⭐ [FEAT], 🍀 지현

#52 [FIX/#51] YearPicker 컴포넌트 수정
  app/src/main/java/com/sopt/withsuhyeon/core/component/picker/YearPicker.kt
Labels: 💙 [UI], 🔧 [FIX], 🌻 윤서

#54 [FEAT/#48] home UI
  app/build.gradle.kts
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonPostScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/FindSuhyeonPostItem.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/navigation/FindSuhyeonNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/component/HomeCardItem.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainTab.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/res/drawable/img_do_not_disturb.png
  app/src/main/res/drawable/img_megaphone.xml
  app/src/main/res/drawable/img_seek_and_hide.png
  app/src/main/res/drawable/img_study_cafe.png
  app/src/main/res/raw/test.lottie
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🛠️ [CHORE], 💛 COMPOSE, ⭐ [FEAT], 💙 [UI], 🍀 지현

#62 [FEAT/#61] 홈 뷰모델 작업
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/state/HomeState.kt
Labels: 💛 COMPOSE, ⭐ [FEAT], 🍀 지현

#66 [FEAT/#65] home api 연결
  app/build.gradle.kts
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/GalleryCategoryBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/CategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/NewCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/network/TokenManager.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/image/ContentUriRequestBody.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/image/createImagePart.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/GalleryDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/HomeDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/GalleryDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/HomeDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/ApiModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/DataSourceModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/NetworkModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/RepositoryModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/SharedPreferencesModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/base/BaseResponse.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/request/RequestUploadGalleryDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseGalleryCategoriesDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseGalleryPostDetailDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseGalleryTotalDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseHomeDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/GalleryPostDetailMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/HomeMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/GalleryRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/GalleryService.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/HomeService.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/Category.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/Gallery.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/GalleryPostDetailModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/HomeModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/PostItemModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/GalleryRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/HomeRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryPostDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryPostDetailViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryUploadScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryUploadViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/state/HomeState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainActivity.kt
Labels: 💛 COMPOSE, ⭐ [FEAT], 💻 서버 통신, 🍀 지현

#67 [FEAT/#53] 갤러리 뷰 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/DeletePostBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/card/GalleryMainCardItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/chip/NewCategoryChip.kt
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/image/downloadImage.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/GalleryDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/GalleryDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/GalleryPostDetailMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/GalleryRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/GalleryService.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/GalleryPostDetailModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/GalleryRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryPostDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryPostDetailViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💻 서버 통신, 🌻 윤서

#75 [FEAT/#69] 마이페이지 조회 API 연동
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/MyPageDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/MyPageDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/ApiModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/DataSourceModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/RepositoryModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseMyPageInfoDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/MyPageInfoMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/MyPageRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/MyPageService.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/MyPageInfo.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/MyPageRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/MyPageScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/MyPageViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 💻 서버 통신, 🌻 윤서

#70 [FEAT/#64] 회원가입 ViewModel 작업
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/Finish.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/GenderSelectScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/NicknameAuthentication.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/PhoneNumberAuthenticationScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/SelectLocation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/SelectProfile.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/TermsOfUseScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/YearOfBirthScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/navigation/OnBoardingNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/LoginState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/SignUpState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/SignUpViewModel.kt
Labels: ⭐ [FEAT], 🔧 [FIX], 🐬 세호

#77 [FEAT/#68] 수현이 찾기 api연결
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/LocationBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/menu/LocationMenu.kt
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/FindSuhyeonDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/FindSuhyeonDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/request/RequestFindSuhyeonPostUploadDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseFindSuhyeonPostDetailDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseHomeDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/FindSuhyeonPostDetailMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/FindSuhyeonPostUploadMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/FindSuhyeonRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/FindSuhyeonService.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/ChatRoomInfoModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/FindSuhyeonPostDetailModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/FindSuhyeonPostUploadModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/PostDatilInfoModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/PostItemModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/FindSuhyeonRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonPostScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DetailMeetingInformation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/FindSuhyeonPostItem.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/navigation/FindSuhyeonNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/state/FindSuhyeonPostState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/state/FindSuhyeonUploadState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonPostViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonUploadViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/res/drawable/img_boy_default.xml
  app/src/main/res/drawable/img_boy_selected.xml
  app/src/main/res/drawable/img_girl_default.xml
Labels: ⭐ [FEAT], 💻 서버 통신, 🍀 지현

#80 [FEAT/#74] 로그인 api연결
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasource/LoginDataSource.kt
  app/src/main/java/com/sopt/withsuhyeon/data/datasourceimpl/LoginDataSourceImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/ApiModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/DataSourceModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/di/RepositoryModule.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/request/RequestLoginDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseLoginDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/LoginTokenMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/LoginRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/data/service/LoginService.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/LoginTokenModel.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/LoginRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/FinishLogin.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/FinishSignUp.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/Login.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/navigation/OnBoardingNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/LoginState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💻 서버 통신, 🐬 세호

#88 [HOTFIX/#86] QA - 온보딩 / 차단 / 기타 반영
  app/src/main/java/com/sopt/withsuhyeon/core/component/listitem/BlockPhoneNumberItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/profile/PostProfileInfoRow.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/KeyStorage.kt
  app/src/main/java/com/sopt/withsuhyeon/core/util/regex/PhoneNumberValid.kt
  app/src/main/java/com/sopt/withsuhyeon/data/repositoryimpl/SignUpRepositoryImpl.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/repository/SignUpRepository.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/BlockUser.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/FinishLogin.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/FinishSignUp.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/GenderSelectScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/Login.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/NicknameAuthentication.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/OnBoardingScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/PhoneNumberAuthenticationScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/SelectLocation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/SelectProfile.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/TermsOfUseScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/YearOfBirthScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/navigation/OnBoardingNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/LoginState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/SignUpState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 😮 [HOTFIX], 🔧 [FIX], 🐬 세호

#90 [FIX/#50] 갤러리 상세 UI 수정
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryUploadScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
Labels: 💙 [UI], 🔧 [FIX], 🍀 지현

#93 [HOTFIX/#92] 자동로그인
  app/src/main/java/com/sopt/withsuhyeon/core/network/TokenManager.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/FinishSignUp.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/navigation/OnBoardingNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/splash/Splash.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/splash/SplashNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/splash/SplashViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/splash/state/SplashState.kt
Labels: 😮 [HOTFIX]

#98 [HOTFIX/#96] 차단 바텀시트 닉네임 추가
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/BlockBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseHomeDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/mapper/HomeMapper.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/HomeModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/state/HomeState.kt
  app/src/main/res/values/strings.xml
Labels: 😮 [HOTFIX], 🐬 세호

#97 [hotfix/#95] qa 반영 (남여, 남의 게시물)
  app/src/main/java/com/sopt/withsuhyeon/core/network/TokenManager.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonPostScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/FindSuhyeonPostItem.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/state/HomeState.kt
Labels: 💛 COMPOSE, 😮 [HOTFIX], 🍀 지현

#101 [HOTFIX/#100] 지역 선택 버튼 활성화, 인증번호 버튼 활성화
  app/src/main/java/com/sopt/withsuhyeon/core/component/button/BasicButtonForTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/SelectLocation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/SignUpState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/SignUpViewModel.kt
Labels: 💛 COMPOSE, 😮 [HOTFIX], 🍀 지현

#105 [HOTFIX/#104] 회원가입 로그인 차단 TextField 길이 제한
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/BlockUser.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/Login.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/PhoneNumberAuthenticationScreen.kt
Labels: 😮 [HOTFIX], 🐬 세호

#108 [CHORE/#106] UI 수정사항 및 기능 수정사항 반영
  app/src/main/java/com/sopt/withsuhyeon/core/component/bottomsheet/LocationBottomSheet.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/navigation/FindSuhyeonNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonUploadViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/navigation/GalleryNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/HomeScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
Labels: 🛠️ [CHORE], 💛 COMPOSE, 💙 [UI], 🍀 지현

#109 [HOTFIX/#107] Emergency QA
  app/src/main/java/com/sopt/withsuhyeon/core/util/regex/NicknameValid.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/home/navigation/HomeNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/BlockUser.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/GenderSelectScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/Login.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/PhoneNumberAuthenticationScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/BlockUserViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable/img_red_suma.xml
Labels: 😮 [HOTFIX], 🐬 세호

#110 [FEAT/#76] 채팅 구현
  app/src/main/java/com/sopt/withsuhyeon/core/component/list/TotalChatRoomList.kt
  app/src/main/java/com/sopt/withsuhyeon/core/component/listitem/ChatRoomListItem.kt
  app/src/main/java/com/sopt/withsuhyeon/core/navigation/RouteModel.kt
  app/src/main/java/com/sopt/withsuhyeon/data/dto/response/ResponseChatRoomsDto.kt
  app/src/main/java/com/sopt/withsuhyeon/data/socket/WebSocketClient.kt
  app/src/main/java/com/sopt/withsuhyeon/domain/entity/ChatRoomDetailModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatRoomRealScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatRoomRealViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatRoomScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/ChatViewModel.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/chat/navigation/ChatNavigation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/MainNavigator.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/main/component/MainNavHost.kt
Labels: ⭐ [FEAT], 💻 서버 통신, 🌻 윤서

#113 [CHORE/#111] 수현이 찾기 세 붙이기, 카테고리 필터링
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/DetailMeetingInformation.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/component/drpodown/DetailMeetingInformationDropDown.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/gallery/GalleryScreen.kt
Labels: 🛠️ [CHORE], 💛 COMPOSE, 💙 [UI], 🍀 지현

#115 [FIX/#114] 닉네임 텍스트필드 수정
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/NicknameAuthentication.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/state/SignUpState.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/onboarding/viewmodel/SignUpViewModel.kt
Labels: 😮 [HOTFIX], 🐬 세호

#116 [CHORE/#111] 텍스트 필드 제약사항 수정
  app/src/main/java/com/sopt/withsuhyeon/core/component/textfield/BasicLongTextField.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/FindSuhyeonUploadDetailScreen.kt
  app/src/main/java/com/sopt/withsuhyeon/feature/findsuhyeon/viewmodel/FindSuhyeonUploadViewModel.kt
Labels: 🛠️ [CHORE], 💛 COMPOSE, 💙 [UI], 🍀 지현
